name: .NET Core CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore lab4.2/*.sln

    - name: Build
      run: dotnet build lab4.2/*.sln --no-restore

    - name: Test
      run: dotnet test lab4.2/*.sln --no-build --verbosity normal